/******************************************************************************
*  G711_Select.s developed by AccelWork Inc. for Microchip Technology Inc. 
*  Copyright (c) 2005 by Microchip. All rights are reserved. 
*  
*  This Copyright notice may not be removed or modified without prior written 
*  consent of Microchip Technology Inc. 
******************************************************************************/

/******************************************************************************
*  G711_Select.s
*
*  Description:
*    This file is generated by dsPIC33F Speech Encoder Utility Version 1.00
*    It contains the ALAW compressed data for a 8kHz,16-bit speech signal.The
*    output array represents a 64kbps encoded bit stream.
*
*    Speech Encoder Utility settings:
*       Input Source:  Select1_8K.wav
*       Output Array:  G711_Select
*       Array Size:    513 bytes                 
*       Target Memory: Program Memory
*       LAW:           ALAW
*
*    Modification History:
*
*       Date           Author              Description
*       ----           ------              -----------
*
*    Dec-16-2005    Taruna Singh		   Created
*    Dec-20-2005    Taruna Singh		   Ready for Alpha Release
*
******************************************************************************/

/* There are 171 elements in the data array. */
    
/* Data file for storing 24-bit constants in program memory */

.global _G711_Select

.section .G711, code
_G711_Select:
.pword 0xD555D5,  0x555555,  0x9998F8,  0x0415CA,  0x056E17,  0x019DED
.pword 0xECB4DF,  0x0587FD,  0xC07D0A,  0x88E812,  0xE0F398,  0x480004
.pword 0x861804,  0xB58B8D,  0x142435,  0xB4858D,  0x1A3DEF,  0x0C6D89
.pword 0xF18F99,  0x0D85ED,  0xB60738,  0x17EDB1,  0x0462F0,  0x0499EF
.pword 0x85831A,  0x7F121D,  0x84FD66,  0x7E6091,  0x68175C,  0xEC95E1
.pword 0x1A66E4,  0x91F71C,  0x469490,  0xF24C14,  0xE2DB74,  0xD56374
.pword 0xFF7A74,  0xCDF6E0,  0x496E7C,  0xD040C8,  0xD5FCE2,  0x6DD2FC
.pword 0x50DE65,  0x75C9D5,  0xF14761,  0x9995F7,  0x111DC6,  0x7F1B11
.pword 0xE6B789,  0x1F350A,  0xB2B094,  0x093D17,  0x876813,  0x9A8DB4
.pword 0x3E307F,  0xB38A18,  0x0AD989,  0x866137,  0xDE9D87,  0x4F161F
.pword 0xEAC976,  0xC4E6E7,  0x6B0207,  0x859B96,  0x03928E,  0x1E8660
.pword 0x19E800,  0xB4950B,  0x73EB80,  0x7E340C,  0xE99780,  0x056290
.pword 0x545E17,  0x8085DC,  0x636A5D,  0x951807,  0x9FF594,  0x1B6799
.pword 0x43566B,  0xEC93F8,  0x6D7A42,  0xFE616A,  0xCE929D,  0x121F15
.pword 0x999C55,  0x1067ED,  0x5A7915,  0xF8E8E7,  0x774DD0,  0x417274
.pword 0xC4CEF5,  0x4DC0F6,  0xD65F4A,  0x795FDC,  0xFC7761,  0xE0EBEF
.pword 0x666146,  0xF84764,  0x74F4E0,  0x41777C,  0xC2E5F4,  0x545E46
.pword 0xC6D352,  0x457450,  0x5E58D7,  0x7E6546,  0xFAFBF5,  0x6057E4
.pword 0x5BD778,  0xE7E75F,  0x475457,  0xCB7A6D,  0xFAFEFF,  0x4870C4
.pword 0xF5F9C6,  0x7E7874,  0xC2F446,  0x949045,  0x4C1446,  0xDB74F2
.pword 0x6374E2,  0x7A74D5,  0xF6E0FF,  0x6E7CCD,  0x40C849,  0xFCE2D0
.pword 0xD2FCD5,  0xDE656D,  0xC9D550,  0x476175,  0x95F7F1,  0x1DC699
.pword 0x1B1111,  0xB7897F,  0x350AE6,  0xB0941F,  0x3D17B2,  0x681309
.pword 0x8DB487,  0x307F9A,  0x8A183E,  0xD989B3,  0x61370A,  0x9D8786
.pword 0x161FDE,  0xC9764F,  0xE6E7EA,  0x0207C4,  0x9B966B,  0x928E85
.pword 0x866003,  0xE8001E,  0x950B19,  0xEB80B4,  0x340C73,  0x97807E
.pword 0x6290E9,  0x5E1705,  0x85DC54,  0x6A5D80,  0x180763,  0xF59495
.pword 0x67999F,  0x566B1B,  0x93F843,  0x7A42EC,  0x616A6D,  0x929DFE
.pword 0x1F15CE,  0x9C5512,  0x00ED99        
