REM Remove unnecessary files generated by compiler in both the 
REM MPLAB 8 and MPLAB X project directories.

echo Removing *.$$$ files...
del project.8\*.$$$ /f /q /s
echo.

echo Removing *.as files...
del project.8\*.as /f /q /s
echo.

echo Removing *.bkx files...
del project.8\*.bkx /f /q /s
echo.

echo Removing *.cce files...
del project.8\*.cce /f /q /s
echo.

echo Removing *.cod files...
del project.8\*.cod /f /q /s
echo.

echo Removing *.cof files...
del project.8\*.cof /f /q /s
echo.

echo Removing *.d files...
del project.8\*.d /f /q /s
echo.

echo Removing *.err files...
del project.8\*.err /f /q /s
echo.

echo Removing *.i files...
del project.8\*.i /f /q /s
echo.

echo Removing *.lde files...
del project.8\*.lde /f /q /s
echo.

echo Removing *.lst files...
del project.8\*.lst /f /q /s
echo.

echo Removing *.obj files...
del project.8\*.obj /f /q /s
echo.

echo Removing *.o files...
del project.8\*.o /f /q /s
echo.

echo Removing *.rlf files...
del project.8\*.rlf /f /q /s
echo.

echo Removing *.sym files...
del project.8\*.sym /f /q /s
echo.

echo Removing *.sdb files...
del project.8\*.sdb /f /q /s
echo.

echo Removing *.wat files...
del project.8\*.wat /f /q /s
echo.

echo Removing *.mcs files...
del project.8\*.mcs /f /q /s
echo.

echo Removing *.mcw files...
del project.8\*.mcw /f /q /s
echo.

echo Removing *.mptags files...
del project.8\*.mptags /f /q /s
echo.

echo Removing *.tagsrc files...
del project.8\*.tagsrc /f /q /s
echo.

echo Removing *.map files...
del project.8\*.map /f /q /s
echo.

echo Removing *.elf files...
del project.8\*.elf /f /q /s
echo.

echo Removing *.dep files...
del project.8\*.dep /f /q /s
echo.

echo Removing *.hxl files...
del project.8\*.hxl /f /q /s
echo.

echo Removing *.p1 files...
del project.8\*.p1 /f /q /s
echo.

echo Removing *.pre files...
del project.8\*.pre /f /q /s
echo.

echo Removing funclist file...
del project.8\funclist /f /q /s
echo.

echo Removing funclist file...
del project.X\funclist /f /q /s
echo.

rd project.X\build              /S /Q
rd project.X\dist               /S /Q
rd project.X\nbproject\private  /S /Q

echo Done.