/*****************************************************************************
 * FileName:        ID.h
 * Dependencies:    See Includes Section
 * Processor:       PIC24, PIC32
 * Compiler:       	MPLAB C30 V3.00, MPLAB C32
 * Linker:          MPLAB LINK30, MPLAB LINK32
 * Company:         Microchip Technology Incorporated
 *
 *
 * Copyright © 2011 Microchip Technology Inc.  All rights reserved.
 * Microchip licenses to you the right to use, modify, copy and distribute
 * Software only when embedded on a Microchip microcontroller or digital
 * signal controller, which is integrated into your product or third party
 * product (pursuant to the sublicense terms in the accompanying license
 * agreement).  
 *
 * You should refer to the license agreement accompanying this Software
 * for additional information regarding your rights and obligations.
 *
 * SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
 * KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
 * OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
 * PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
 * OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
 * BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
 * DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
 * INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
 * COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
 * CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
 * OR OTHER SIMILAR COSTS.
 *
 *****************************************************************************/
#ifndef ID_H
#define ID_H

typedef enum
{
    MAIN_SCREEN_ID_PANEL_BUT = 10,
    MAIN_SCREEN_ID_SLIDE_SHOW_BUT,
    MAIN_SCREEN_ID_PERFORMANCE_BUT,
    MAIN_SCREEN_ID_CONFIG_BUT,
    MAIN_SCREEN_ID_INFO_BUT,
    MAIN_SCREEN_ID_UPLOAD_BUT,
    MAIN_SCREEN_ID_ANALOG_CLOCK,

    INFO_SCREEN_ID_STATIC_TXT,

    PERFORMANCE_SCREEN_ID_COLOR_BUT,
    PERFORMANCE_SCREEN_ID_SPEED_BUT,
    PERFORMANCE_SCREEN_ID_GRADIENT_BUT,
    PERFORMANCE_SCREEN_ID_BLENDING_BUT,
    PERFORMANCE_SCREEN_ID_EXIT_BUT,

    CONFIG_SCREEN_ID_BACKGROUND_BUT,
    CONFIG_SCREEN_ID_ALPHA_BUT,
    CONFIG_SCREEN_ID_PALETTE_BUT,
    CONFIG_SCREEN_ID_BACKLIGHT_BUT,
    CONFIG_SCREEN_ID_PLUS_BUT,
    CONFIG_SCREEN_ID_MINUS_BUT,

    PANEL_SCREEN_ID_COMFORT_BUT,
    PANEL_SCREEN_ID_LIGHTING_BUT,
    PANEL_SCREEN_ID_SECURITY_BUT,
    PANEL_SCREEN_ID_ENERGY_USAGE_BUT,
    PANEL_SCREEN_ID_EXIT_BUT,

    COMFORT_SCREEN_ID_COOL_STATIC_TXT,
    COMFORT_SCREEN_ID_HEAT_STATIC_TXT,
    COMFORT_SCREEN_ID_LEFT_ARROW_BUT,
    COMFORT_SCREEN_ID_RIGHT_ARROW_BUT,
    COMFORT_SCREEN_ID_AUTO_BUT,
    COMFORT_SCREEN_ID_HEAT_BUT,
    COMFORT_SCREEN_ID_OFF_BUT,
    COMFORT_SCREEN_ID_COOL_BUT,
    COMFORT_SCREEN_ID_SYSTEM_MODE_GROUP_BOX,
    COMFORT_SCREEN_ID_FAN_MODE_GROUP_BOX,
    COMFORT_SCREEN_ID_FAN_ON_BUT,
    COMFORT_SCREEN_ID_FAN_AUTO_BUT,
    COMFORT_SCREEN_ID_COOL_MINUS_BUT,
    COMFORT_SCREEN_ID_HEAT_MINUS_BUT,
    COMFORT_SCREEN_ID_COOL_PLUS_BUT,
    COMFORT_SCREEN_ID_HEAT_PLUS_BUT,

    SERCURITY_SCREEN_ID_DISARMED_BUT,
    SERCURITY_SCREEN_ID_ARMED_BUT,
    SERCURITY_SCREEN_ID_SLEEPING_BUT,
    SERCURITY_SCREEN_ID_VACATION_BUT,
    SERCURITY_SCREEN_ID_ENTERTAINING_BUT,
    SERCURITY_SCREEN_ID_CODE_EDIT_BOX,
    // Ordering of these IDs must remain
    SERCURITY_SCREEN_ID_KEYPAD_0_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_1_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_2_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_3_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_4_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_5_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_6_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_7_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_8_BUT,
    SERCURITY_SCREEN_ID_KEYPAD_9_BUT,
    // End of the ID ordering
    SERCURITY_SCREEN_ID_CLEAR_BUT,
    SERCURITY_SCREEN_ID_ENTER_BUT,

    ENERGY_SCREEN_ID_CHART

}GOL_IDS;

#endif
