@echo off
REM Remove files generated by compiler in this directory
REM and all subdirectories.

:start
ECHO Erase all temp data? y or n?
:loop
set /p choice=
if not '%choice%'=='' set choice=%choice:~0,1%
if '%choice%'=='y' goto yes
if '%choice%'=='n' goto no
ECHO "%choice%" is not valid please try again
goto loop

:yes
cd ".."

ECHO *****************************************************************************
ECHO Removing USB Device - Audio - MIDI
ECHO *****************************************************************************
cd "USB Device - Audio - MIDI\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO *****************************************************************************
ECHO Removing USB Device - Audio - Microphone
ECHO *****************************************************************************
cd "USB Device - Audio - Microphone\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO *****************************************************************************
ECHO Removing USB Device - Audio - Speaker
ECHO *****************************************************************************
cd "USB Device - Audio - Speaker\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO *****************************************************************************
ECHO Removing PIC32 HID bootloader
ECHO *****************************************************************************
cd "USB Device - Bootloaders\HID - Bootloader\HID Bootloader - Firmware for PIC32MX460F512L Family Devices"
call "CleanUp.bat"
cd "..\..\.."

ECHO *****************************************************************************
ECHO Removing USB Device - CDC - Basic Demo information
ECHO *****************************************************************************
cd "USB Device - CDC - Basic Demo\CDC - Basic Demo - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO *****************************************************************************
ECHO Removing USB Device - CDC - Serial Emulator
ECHO *****************************************************************************
cd "USB Device - CDC - Serial Emulator\CDC - Serial Emulator"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Composite - HID + MSD
ECHO *****************************************************************************
cd "USB Device - Composite - HID + MSD\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Composite - MSD + CDC
ECHO *****************************************************************************
cd "USB Device - Composite - MSD + CDC\Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Simple Custom Demo
ECHO *****************************************************************************
cd "USB Device - HID - Custom Demos\Generic HID - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Digitizers\Multi Touch - Firmware
ECHO *****************************************************************************
cd "USB Device - HID - Digitizers\Multi Touch - Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Digitizers\Single Touch - Firmware
ECHO *****************************************************************************
cd "USB Device - HID - Digitizers\Single Touch - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Joystick\Firmware
ECHO *****************************************************************************
cd "USB Device - HID - Joystick\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Keyboard
ECHO *****************************************************************************
cd "USB Device - HID - Keyboard\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Mouse
ECHO *****************************************************************************
cd "USB Device - HID - Mouse\HID - Mouse - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - HID - Uninterruptible Power Supply\Firmware
ECHO *****************************************************************************
cd "USB Device - HID - Uninterruptible Power Supply\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Mass Storage - SD Card data logger
ECHO *****************************************************************************
cd "USB Device - Mass Storage - SD Card data logger\Mass Storage - Data Logger - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - LibUSB - Generic Driver Demo\LibUSB Simple Demo - Firmware
ECHO *****************************************************************************
cd "USB Device - LibUSB - Generic Driver Demo\LibUSB Simple Demo - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Mass Storage - Internal Flash
ECHO *****************************************************************************
cd "USB Device - Mass Storage - Internal Flash\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Mass Storage - SD Card data logger\Mass Storage - Data Logger - Firmware
ECHO *****************************************************************************
cd "USB Device - Mass Storage - SD Card data logger\Mass Storage - Data Logger - Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - Mass Storage - SD Card reader
ECHO *****************************************************************************
cd "USB Device - Mass Storage - SD Card reader\Mass Storage - SD Card Reader - Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - MCHPUSB - Generic Driver Demo
ECHO *****************************************************************************
cd "USB Device - MCHPUSB - Generic Driver Demo\Generic Driver Demo - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - WinUSB - Generic Driver Demo
ECHO *****************************************************************************
cd "USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Device - WinUSB - High Bandwidth Demo\WinUSB High Bandwidth Demo - Firmware
ECHO *****************************************************************************
cd "USB Device - WinUSB - High Bandwidth Demo\WinUSB High Bandwidth Demo - Firmware"
call "CleanUp.bat"
cd "..\.."


ECHO.
ECHO *****************************************************************************
ECHO Removing USB Dual Role - MSD host + HID device\Firmware
ECHO *****************************************************************************
cd "USB Dual Role - MSD host + HID device\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Bootloaders\Mass Storage Bootloader
ECHO *****************************************************************************
cd "USB Host - Bootloaders\Mass Storage Bootloader"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - CDC - Serial Demo\ACM - Serial RS232 Demo
ECHO *****************************************************************************
cd "USB Host - CDC - Serial Demo\ACM - Serial RS232 Demo"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Charger - Simple Charger\Simple Charger
ECHO *****************************************************************************
cd "USB Host - Charger - Simple Charger\Simple Charger"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - HID - Keyboard
ECHO *****************************************************************************
cd "USB Host - HID - Keyboard\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - HID - Mouse\Firmware
ECHO *****************************************************************************
cd "USB Host - HID - Mouse\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Mass Storage - Simple Demo\Firmware
ECHO *****************************************************************************
cd "USB Host - Mass Storage - Simple Demo\Firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Mass Storage - Thumb Drive Data Logger
ECHO *****************************************************************************
cd "USB Host - Mass Storage - Thumb Drive Data Logger\Mass Storage - Thumb Drive Data Logger"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - MCHPUSB - Generic Driver Demo
ECHO *****************************************************************************
cd "USB Host - MCHPUSB - Generic Driver Demo\firmware"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Printer - Print Screen Demo
ECHO *****************************************************************************
cd "USB Host - Printer - Print Screen Demo\Print Screen Demo"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Printer - Simple Full Sheet Demo
ECHO *****************************************************************************
cd "USB Host - Printer - Simple Full Sheet Demo\Simple Full Sheet Demo"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Printer - Simple POS Demo
ECHO *****************************************************************************
cd "USB Host - Printer - Simple POS Demo\Simple POS Demo"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - Printer and HID - MASTERs 2008 Demo\MASTERs 2008 Printer Demo
ECHO *****************************************************************************
cd "USB Host - Printer and HID - MASTERs 2008 Demo\MASTERs 2008 Printer Demo"
call "CleanUp.bat"
cd "..\.."

ECHO.
ECHO *****************************************************************************
ECHO Removing USB Host - MCHPUSB - Generic Driver Demo
ECHO *****************************************************************************
cd "USB OTG - MCHPUSB - Generic Driver Demo\firmware"
call "CleanUp.bat"
cd "..\.."

:no
echo Done.