#############################################################################
# Makefile for building: HIDBootloader
# Generated by qmake (2.01a) (Qt 4.7.0) on: Mon Oct 10 17:03:14 2011
# Project:  HIDBootloader.pro
# Template: subdirs
# Command: c:\qt\2010.05\qt\bin\qmake.exe -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile HIDBootloader.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qt\2010.05\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-HIDAPI \
		sub-Bootloader

HIDAPI\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) HIDAPI\ $(MKDIR) HIDAPI\ 
	cd HIDAPI\ && $(QMAKE) c:\Users\c13736\Desktop\App Libs v2011-10\Microchip Solutions\USB\Device - Bootloaders\HID\Software - Cross Platform\HIDAPI\HIDAPI.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-HIDAPI-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) HIDAPI\ $(MKDIR) HIDAPI\ 
	cd HIDAPI\ && $(QMAKE) c:\Users\c13736\Desktop\App Libs v2011-10\Microchip Solutions\USB\Device - Bootloaders\HID\Software - Cross Platform\HIDAPI\HIDAPI.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-HIDAPI: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE)
sub-HIDAPI-make_default-ordered: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) 
sub-HIDAPI-make_default: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) 
sub-HIDAPI-make_first-ordered: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) first
sub-HIDAPI-make_first: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) first
sub-HIDAPI-all-ordered: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) all
sub-HIDAPI-all: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) all
sub-HIDAPI-clean-ordered: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) clean
sub-HIDAPI-clean: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) clean
sub-HIDAPI-distclean-ordered: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) distclean
sub-HIDAPI-distclean: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) distclean
sub-HIDAPI-install_subtargets-ordered: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) install
sub-HIDAPI-install_subtargets: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) install
sub-HIDAPI-uninstall_subtargets-ordered: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-HIDAPI-uninstall_subtargets: HIDAPI\$(MAKEFILE) FORCE
	cd HIDAPI\ && $(MAKE) -f $(MAKEFILE) uninstall
Bootloader\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Bootloader\ $(MKDIR) Bootloader\ 
	cd Bootloader\ && $(QMAKE) c:\Users\c13736\Desktop\App Libs v2011-10\Microchip Solutions\USB\Device - Bootloaders\HID\Software - Cross Platform\Bootloader\Bootloader.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-Bootloader-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Bootloader\ $(MKDIR) Bootloader\ 
	cd Bootloader\ && $(QMAKE) c:\Users\c13736\Desktop\App Libs v2011-10\Microchip Solutions\USB\Device - Bootloaders\HID\Software - Cross Platform\Bootloader\Bootloader.pro -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-Bootloader: Bootloader\$(MAKEFILE) FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE)
sub-Bootloader-make_default-ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-make_default-ordered  FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) 
sub-Bootloader-make_default: Bootloader\$(MAKEFILE) FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) 
sub-Bootloader-make_first-ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-make_first-ordered  FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) first
sub-Bootloader-make_first: Bootloader\$(MAKEFILE) FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) first
sub-Bootloader-all-ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-all-ordered  FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) all
sub-Bootloader-all: Bootloader\$(MAKEFILE) FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) all
sub-Bootloader-clean-ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-clean-ordered  FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) clean
sub-Bootloader-clean: Bootloader\$(MAKEFILE) FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) clean
sub-Bootloader-distclean-ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-distclean-ordered  FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) distclean
sub-Bootloader-distclean: Bootloader\$(MAKEFILE) FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) distclean
sub-Bootloader-install_subtargets-ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-install_subtargets-ordered  FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) install
sub-Bootloader-install_subtargets: Bootloader\$(MAKEFILE) FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) install
sub-Bootloader-uninstall_subtargets-ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-uninstall_subtargets-ordered  FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-Bootloader-uninstall_subtargets: Bootloader\$(MAKEFILE) FORCE
	cd Bootloader\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: HIDBootloader.pro  c:/Qt/2010.05/qt/mkspecs/win32-g++/qmake.conf c:/Qt/2010.05/qt/mkspecs/qconfig.pri \
		c:/Qt/2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		c:/Qt/2010.05/qt/mkspecs/features/qt_functions.prf \
		c:/Qt/2010.05/qt/mkspecs/features/qt_config.prf \
		c:/Qt/2010.05/qt/mkspecs/features/exclusive_builds.prf \
		c:/Qt/2010.05/qt/mkspecs/features/default_pre.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/default_pre.prf \
		c:/Qt/2010.05/qt/mkspecs/features/release.prf \
		c:/Qt/2010.05/qt/mkspecs/features/debug_and_release.prf \
		c:/Qt/2010.05/qt/mkspecs/features/default_post.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/default_post.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/rtti.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/exceptions.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/stl.prf \
		c:/Qt/2010.05/qt/mkspecs/features/shared.prf \
		c:/Qt/2010.05/qt/mkspecs/features/warn_on.prf \
		c:/Qt/2010.05/qt/mkspecs/features/qt.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/thread.prf \
		c:/Qt/2010.05/qt/mkspecs/features/moc.prf \
		c:/Qt/2010.05/qt/mkspecs/features/win32/windows.prf \
		c:/Qt/2010.05/qt/mkspecs/features/resources.prf \
		c:/Qt/2010.05/qt/mkspecs/features/uic.prf \
		c:/Qt/2010.05/qt/mkspecs/features/yacc.prf \
		c:/Qt/2010.05/qt/mkspecs/features/lex.prf \
		c:/Qt/2010.05/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile HIDBootloader.pro
c:\Qt\2010.05\qt\mkspecs\qconfig.pri:
c:\Qt\2010.05\qt\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\2010.05\qt\mkspecs\features\qt_functions.prf:
c:\Qt\2010.05\qt\mkspecs\features\qt_config.prf:
c:\Qt\2010.05\qt\mkspecs\features\exclusive_builds.prf:
c:\Qt\2010.05\qt\mkspecs\features\default_pre.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\default_pre.prf:
c:\Qt\2010.05\qt\mkspecs\features\release.prf:
c:\Qt\2010.05\qt\mkspecs\features\debug_and_release.prf:
c:\Qt\2010.05\qt\mkspecs\features\default_post.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\default_post.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\rtti.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\exceptions.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\stl.prf:
c:\Qt\2010.05\qt\mkspecs\features\shared.prf:
c:\Qt\2010.05\qt\mkspecs\features\warn_on.prf:
c:\Qt\2010.05\qt\mkspecs\features\qt.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\thread.prf:
c:\Qt\2010.05\qt\mkspecs\features\moc.prf:
c:\Qt\2010.05\qt\mkspecs\features\win32\windows.prf:
c:\Qt\2010.05\qt\mkspecs\features\resources.prf:
c:\Qt\2010.05\qt\mkspecs\features\uic.prf:
c:\Qt\2010.05\qt\mkspecs\features\yacc.prf:
c:\Qt\2010.05\qt\mkspecs\features\lex.prf:
c:\Qt\2010.05\qt\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile HIDBootloader.pro

qmake_all: sub-HIDAPI-qmake_all sub-Bootloader-qmake_all FORCE

make_default: sub-HIDAPI-make_default-ordered sub-Bootloader-make_default-ordered FORCE
make_first: sub-HIDAPI-make_first-ordered sub-Bootloader-make_first-ordered FORCE
all: sub-HIDAPI-all-ordered sub-Bootloader-all-ordered FORCE
clean: sub-HIDAPI-clean-ordered sub-Bootloader-clean-ordered FORCE
distclean: sub-HIDAPI-distclean-ordered sub-Bootloader-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-HIDAPI-install_subtargets-ordered sub-Bootloader-install_subtargets-ordered FORCE
uninstall_subtargets: sub-HIDAPI-uninstall_subtargets-ordered sub-Bootloader-uninstall_subtargets-ordered FORCE

sub-HIDAPI-sub_Debug_ordered: HIDAPI\$(MAKEFILE)
	cd HIDAPI\ && $(MAKE) debug
sub-Bootloader-sub_Debug_ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-sub_Debug_ordered 
	cd Bootloader\ && $(MAKE) debug
debug: sub-HIDAPI-sub_Debug_ordered sub-Bootloader-sub_Debug_ordered

sub-HIDAPI-sub_Release_ordered: HIDAPI\$(MAKEFILE)
	cd HIDAPI\ && $(MAKE) release
sub-Bootloader-sub_Release_ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-sub_Release_ordered 
	cd Bootloader\ && $(MAKE) release
release: sub-HIDAPI-sub_Release_ordered sub-Bootloader-sub_Release_ordered

sub-HIDAPI-check_ordered: HIDAPI\$(MAKEFILE)
	cd HIDAPI\ && $(MAKE) check
sub-Bootloader-check_ordered: Bootloader\$(MAKEFILE) sub-HIDAPI-check_ordered 
	cd Bootloader\ && $(MAKE) check
check: sub-HIDAPI-check_ordered sub-Bootloader-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

